### ISSUE TITLE
`HistoryTracker` documents not created if `track_create` set to `false`

### ISSUE THREAD

**Issue by Murphydbuffalo** [mongoid/mongoid-history#231]
I have a `User` class with a `budget_boost` field. If I install the gem, set up the `mongoid_history.rb` initializer as follows:
```
Mongoid::History.tracker_class_name = :history_tracker
```

And set up the `history_tracker.rb` model as follows:
```
class HistoryTracker
  include Mongoid::History::Tracker
end
```

And add the following to my `User` model:
```
  include Mongoid::History::Trackable

  ...

  track_history on: %i[budget_boost],
                modifier_field: :modifier,
                modifier_field_inverse_of: :modified,
                modifier_field_optional: true,
                track_create:  false,
                track_update:  false,
                track_destroy: false
```

I do not see any `history_tracks` added to users when I modify their `budget_boost` field, even if the `modifier` association is set.

But if I remove the:
```
track_create:  false,
track_update:  false,
track_destroy: false
```

options, then everything works as expected.

Rails 5.2.0, Ruby 2.6.2, Mongoid History 0.8.1

**Comment by mikwat** [comment]
That sounds like the expected behavior. If you want to track modifications, then enable via `track_update: true` or just don't set it to `false` as it's `true` by default.

The `:modifier` association will track who made the change. According to the readme:
`adds "belongs_to :modifier" to track who made the change, default is :modifier, set to nil to not create modifier_field`

**Comment by Murphydbuffalo** [comment]
Ah sorry, my mistake! I was reading the `track_create` and `track_destroy`, but not `track_update`.
